INSERT INTO TBL_PRODUCT (PRODUCT_PRICE, PRODUCT_NAME) VALUES (30.00, 'CELULAR');
INSERT INTO TBL_PRODUCT (PRODUCT_PRICE, PRODUCT_NAME) VALUES (899.99, 'FONE');
INSERT INTO TBL_PRODUCT (PRODUCT_PRICE, PRODUCT_NAME) VALUES (200.00, 'CAPINHA');
INSERT INTO TBL_PRODUCT (PRODUCT_PRICE, PRODUCT_NAME) VALUES (200.00, 'MAÇA');